const labels = {
  motion_blur:"Смаз от движения",out_of_focus:"Не в фокусе",too_dark:"Слишком темно",overexposed:"Пересвет",compression_or_corruption:"Сжатие / повреждение",obstructed_view:"Обзор закрыт",close_surface:"Стена / объект слишком близко",mostly_ground:"В основном земля",mostly_sky:"В основном небо",inside_vehicle:"Из салона",indoor:"В помещении",vegetation_dominated:"Преобладает зелень",generic_road:"Типовая дорога",repetitive_scene:"Повторяющаяся сцена",no_stable_landmarks:"Нет устойчивых ориентиров",insufficient_scene_context:"Мало окружения",
  distinctive_buildings:"Узнаваемые здания",intersection_or_road_geometry:"Перекрёсток / геометрия дороги",street_furniture:"Уличные объекты",signage_or_text:"Вывески / текст",transit_infrastructure:"Транспортная инфраструктура",distinctive_landscape:"Особый ландшафт",strong_architectural_cues:"Архитектурные признаки",multiple_independent_landmarks:"Несколько независимых ориентиров",
  hold_camera_still:"Держать камеру неподвижно",step_away_from_close_surface:"Отойти от стены / объекта",turn_toward_street:"Повернуть к улице",turn_toward_buildings:"Повернуть к зданиям",include_intersection:"Включить перекрёсток",include_signs:"Включить указатели / вывески",include_wider_field_of_view:"Снять более широкий план",avoid_ground_or_sky:"Не направлять на землю / небо",move_away_from_obstruction:"Обойти препятствие",try_another_direction:"Снять в другом направлении"
};
const form=document.getElementById("annotation-form"),image=document.getElementById("query-image"),loading=document.getElementById("image-loading"),notice=document.getElementById("notice"),action=document.getElementById("retake-action"),saveButton=document.getElementById("save-button");
let currentToken=null;
function showError(message){notice.textContent=message;notice.hidden=false;saveButton.disabled=false}
function clearError(){notice.textContent="";notice.hidden=true}
async function getJson(url,options){const response=await fetch(url,options);let body;try{body=await response.json()}catch{throw new Error("Сервер вернул неверный ответ")};if(!response.ok)throw new Error(body.error||"Не удалось выполнить запрос");return body}
function addChips(container,values){for(const value of values){const label=document.createElement("label"),input=document.createElement("input"),span=document.createElement("span");input.type="checkbox";input.value=value;span.textContent=labels[value]||value;label.append(input,span);container.append(label)}}
async function loadCurrent(){clearError();const data=await getJson("/api/current");document.getElementById("progress-text").textContent=`Оценено ${data.completed} из ${data.total}`;document.getElementById("rater-text").textContent=`Аннотатор: ${data.rater}`;if(data.done){currentToken=null;form.hidden=true;document.getElementById("complete-state").hidden=false;image.hidden=true;loading.hidden=false;loading.textContent="Набор завершён";return}currentToken=data.token;form.reset();action.disabled=true;action.value="";form.hidden=false;document.getElementById("complete-state").hidden=true;image.hidden=true;loading.hidden=false;loading.textContent="Загружаем снимок…";image.onload=()=>{loading.hidden=true;image.hidden=false};image.onerror=()=>{loading.textContent="Не удалось открыть снимок. Сообщи координатору разметки.";showError("Снимок не загружается. Оценка не сохранена.")};image.src=`/image/${encodeURIComponent(currentToken)}`;saveButton.disabled=false}
async function setup(){try{const schema=await getJson("/api/schema");addChips(document.getElementById("reason-options"),schema.reason_labels);addChips(document.getElementById("evidence-options"),schema.positive_evidence_labels);for(const value of schema.retake_actions){const option=document.createElement("option");option.value=value;option.textContent=labels[value]||value;action.append(option)}await loadCurrent()}catch(error){showError(error.message)}}
form.addEventListener("change",event=>{if(event.target.name==="retake"){action.disabled=event.target.value!=="yes";if(action.disabled)action.value=""}});
form.addEventListener("submit",async event=>{event.preventDefault();clearError();const score=form.querySelector('input[name="geolocatability"]:checked'),retake=form.querySelector('input[name="retake"]:checked');if(!score||!retake){showError("Выбери оценку кадра и ответ о повторном снимке.");return}if(retake.value==="yes"&&!action.value){showError("Выбери конкретное действие для повторного снимка.");action.focus();return}const payload={token:currentToken,geolocatability:Number(score.value),reasons:[...document.querySelectorAll('#reason-options input:checked')].map(x=>x.value),positive_evidence:[...document.querySelectorAll('#evidence-options input:checked')].map(x=>x.value),would_request_another_photo:retake.value==="yes",recommended_retake_action:retake.value==="yes"?action.value:null,note:document.getElementById("note").value};saveButton.disabled=true;try{await getJson("/api/annotation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});await loadCurrent();document.querySelector(".assessment").scrollTo({top:0,behavior:"instant"});window.scrollTo({top:0,behavior:"instant"})}catch(error){showError(error.message)}});
document.addEventListener("keydown",event=>{if(event.target.matches("textarea,input,select")||event.altKey||event.metaKey||event.ctrlKey)return;if(/^[0-4]$/.test(event.key)){const radio=form.querySelector(`input[name="geolocatability"][value="${event.key}"]`);if(radio){radio.checked=true;radio.focus()}}});
setup();
